server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/openshop
    username: admin
    password: password
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB